# Generated by Django 3.0.4 on 2020-03-31 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolviOrder',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('pool', models.CharField(max_length=32)),
                ('firstname', models.CharField(max_length=32)),
                ('lastname', models.CharField(max_length=32)),
                ('company', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=8)),
                ('street', models.CharField(max_length=64)),
                ('postcode', models.CharField(max_length=16)),
                ('language', models.CharField(max_length=4)),
                ('phone', models.CharField(max_length=16)),
                ('paid', models.BooleanField()),
                ('create_time', models.DateTimeField()),
                ('paid_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HolviPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='holvi_orders.HolviOrder')),
            ],
        ),
        migrations.CreateModel(
            name='HolviWebshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holvi_webshops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HolviPurchaseAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('answer', models.CharField(max_length=256)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='holvi_orders.HolviPurchase')),
            ],
        ),
        migrations.AddField(
            model_name='holviorder',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='holvi_orders.HolviWebshop'),
        ),
    ]
