# Generated by Django 3.0.4 on 2020-03-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holvi_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holviorder',
            name='city',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='holviorder',
            name='company',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='holviorder',
            name='country',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='holviorder',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holviorder',
            name='email',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='holviorder',
            name='firstname',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='holviorder',
            name='language',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='holviorder',
            name='lastname',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='holviorder',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='holviorder',
            name='paid_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holviorder',
            name='phone',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='holviorder',
            name='pool',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='holviorder',
            name='postcode',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='holviorder',
            name='street',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
