"""
Django settings for OLMap project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import sys
import warnings

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

# Suppress deprecation warnings from dj-rest-auth for django-allauth 65.5.0+ compatibility
warnings.filterwarnings(
    "ignore",
    message=r"app_settings\.(USERNAME_REQUIRED|EMAIL_REQUIRED) is deprecated",
    module="dj_rest_auth.registration.serializers",
)

CONFIG_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.dirname(CONFIG_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False").lower() in ("true", "1", "yes", "on")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        # Only allow fallback in debug mode for development
        SECRET_KEY = "dev-only-secret-key-not-for-production"
    else:
        raise ValueError("DJANGO_SECRET_KEY environment variable must be set in production")

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "citylogistiikka.fvh.io,127.0.0.1,localhost").split(",")


# Application definition

INSTALLED_APPS = [
    "olmap",
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "olmap_config.apps.AdminConfig",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_rename_app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "olmap_config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "olmap_config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.environ.get("POSTGRES_DB", "citylogistiikka_dev"),
        "USER": os.environ.get("POSTGRES_USER", "citylogistiikka"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "citylogistiikka"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
        "OPTIONS": {
            "connect_timeout": 60,
            "options": "-c statement_timeout=300000",  # 5 minutes for long-running migrations
        },
        "CONN_MAX_AGE": 60,
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Helsinki"

USE_I18N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

CORS_ORIGIN_ALLOW_ALL = os.environ.get("DJANGO_CORS_ALLOW_ALL", "False").lower() in ("true", "1", "yes", "on")
CORS_ALLOWED_ORIGINS = (
    os.environ.get("DJANGO_CORS_ALLOWED_ORIGINS", "").split(",")
    if os.environ.get("DJANGO_CORS_ALLOWED_ORIGINS")
    else []
)
CORS_ALLOW_CREDENTIALS = True

STATIC_URL = "/staticfiles/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_URL = "/uploads/"
MEDIA_ROOT = os.path.join(BASE_DIR, "uploads")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    # Rate limiting to prevent brute force and DoS attacks
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
    },
}

REST_AUTH = {
    "USER_DETAILS_SERIALIZER": "olmap.rest.serializers.UserSerializer",
    "PASSWORD_RESET_SERIALIZER": "olmap.rest.serializers.PasswordResetSerializer",
}

LOG_DB_QUERIES = False

if LOG_DB_QUERIES:
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "filters": {
            "require_debug_true": {
                "()": "django.utils.log.RequireDebugTrue",
            }
        },
        "handlers": {
            "console": {
                "level": "DEBUG",
                "filters": ["require_debug_true"],
                "class": "logging.StreamHandler",
            }
        },
        "loggers": {
            "django.db.backends": {
                "level": "DEBUG",
                "handlers": ["console"],
            }
        },
    }

TWILIO = {
    "ACCOUNT_SID": os.environ.get("TWILIO_ACCOUNT_SID", ""),
    "AUTH_TOKEN": os.environ.get("TWILIO_AUTH_TOKEN", ""),
    "SENDER_NR": os.environ.get("TWILIO_SENDER_NR", ""),
}
GATEWAY_API = {
    "KEY": os.environ.get("GATEWAY_API_KEY", ""),
    "SECRET": os.environ.get("GATEWAY_API_SECRET", ""),
    "TOKEN": os.environ.get("GATEWAY_API_TOKEN", ""),
}
SMS_PLATFORM = os.environ.get("SMS_PLATFORM", "None")

FRONTEND_ROOT = os.environ.get("FRONTEND_ROOT", "https://app.olmap.org/")

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Security headers - enabled in production (non-DEBUG) mode
if not DEBUG:
    # HSTS settings - enforce HTTPS
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Redirect HTTP to HTTPS
    SECURE_SSL_REDIRECT = True

    # Prevent MIME type sniffing
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # Secure cookies
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Prevent clickjacking (also set via X-Frame-Options middleware)
    X_FRAME_OPTIONS = "DENY"

ADMINS = [["FVH Django admins", os.environ.get("ADMIN_EMAIL", "django-admins@forumvirium.fi")]]
EMAIL_HOST = os.environ.get("EMAIL_HOST", "localhost")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "25"))

SENTRY_DSN = os.environ.get("SENTRY_DSN", "")
if not DEBUG and SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        # Default to False for privacy/GDPR compliance; set SENTRY_SEND_PII=true to enable
        send_default_pii=os.environ.get("SENTRY_SEND_PII", "False").lower() in ("true", "1", "yes", "on"),
    )

DATETIME_FORMAT = "Y-m-d H:i:s"

SITE_ID = 1

ACCOUNT_EMAIL_VERIFICATION = "none"

# Place a valid google account json here to enable translation of delivery instructions;
# see https://cloud.google.com/translate/docs/setup
GOOGLE_ACCOUNT_JSON = os.path.join(CONFIG_DIR, "google_service_account.json")

try:
    from .local_settings import *  # noqa
except ImportError:
    pass

if "test" in sys.argv:
    DEFAULT_FILE_STORAGE = "inmemorystorage.InMemoryStorage"
    TEST = True
    # INMEMORYSTORAGE_PERSIST = True
else:
    TEST = False
