# Generated by Django 3.0 on 2019-12-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0001_initial'),
    ]

    operations = []
