# Generated by Django 3.0 on 2019-12-17 14:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0004_auto_20191216_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
