# Generated by Django 3.0.2 on 2020-01-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0008_auto_20200124_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmimagenote',
            name='hidden_reason',
            field=models.TextField(blank=True, help_text='If reviewer decides to hide the note, document reason here.'),
        ),
    ]
