# Generated by Django 3.0.2 on 2020-02-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0009_auto_20200124_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmimagenote',
            name='osm_features',
            field=models.ManyToManyField(blank=True, to='fvh_courier.OSMFeature'),
        ),
    ]
