# Generated by Django 3.0.3 on 2020-02-18 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0011_add_reviewer_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osmfeature',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('handrail', models.BooleanField(blank=True, null=True)),
                ('ramp', models.BooleanField(blank=True, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=1, help_text='In meters', max_digits=3, null=True)),
                ('incline', models.CharField(blank=True, choices=[['up', 'up'], ['down', 'down']], help_text='From street level', max_length=32)),
                ('image_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fvh_courier.OSMImageNote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=64)),
                ('housenumber', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=8)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('opening_hours', models.CharField(blank=True, max_length=64)),
                ('level', models.CharField(blank=True, help_text='Floor(s), e.g. 1-3', max_length=8)),
                ('type', models.CharField(blank=True, help_text='See https://wiki.openstreetmap.org/wiki/Key:shop', max_length=32)),
                ('image_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fvh_courier.OSMImageNote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=64)),
                ('housenumber', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=8)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('opening_hours', models.CharField(blank=True, max_length=64)),
                ('level', models.CharField(blank=True, help_text='Floor(s), e.g. 1-3', max_length=8)),
                ('type', models.CharField(blank=True, choices=[['association', 'association'], ['company', 'company'], ['diplomatic', 'diplomatic'], ['educational_institution', 'educational_institution'], ['government', 'government']], max_length=32)),
                ('image_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fvh_courier.OSMImageNote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageNoteTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64)),
                ('image_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='fvh_courier.OSMImageNote')),
            ],
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(blank=True, choices=[['yes', 'yes'], ['private', 'private'], ['delivery', 'delivery'], ['no', 'no']], max_length=32)),
                ('width', models.DecimalField(blank=True, decimal_places=1, help_text='In meters', max_digits=3, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, help_text='In meters', max_digits=3, null=True)),
                ('buzzer', models.BooleanField(default=False)),
                ('keycode', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('opening_hours', models.CharField(blank=True, max_length=64)),
                ('lift_gate', models.BooleanField(default=False)),
                ('image_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fvh_courier.OSMImageNote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=64)),
                ('housenumber', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=8)),
                ('access', models.CharField(blank=True, choices=[['yes', 'yes'], ['private', 'private'], ['delivery', 'delivery'], ['no', 'no']], max_length=32)),
                ('width', models.DecimalField(blank=True, decimal_places=1, help_text='In meters', max_digits=3, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, help_text='In meters', max_digits=3, null=True)),
                ('buzzer', models.BooleanField(default=False)),
                ('keycode', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('opening_hours', models.CharField(blank=True, max_length=64)),
                ('type', models.CharField(blank=True, choices=[['main', 'main'], ['secondary', 'secondary'], ['service', 'service'], ['staircase', 'staircase']], max_length=32)),
                ('wheelchair', models.BooleanField(default=False)),
                ('loadingdock', models.BooleanField(default=False)),
                ('image_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fvh_courier.OSMImageNote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Barrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[['fence', 'fence'], ['wall', 'wall'], ['block', 'block'], ['bollard', 'bollard']], max_length=32)),
                ('image_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fvh_courier.OSMImageNote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=64)),
                ('housenumber', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=8)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('opening_hours', models.CharField(blank=True, max_length=64)),
                ('level', models.CharField(blank=True, help_text='Floor(s), e.g. 1-3', max_length=8)),
                ('type', models.CharField(help_text='See https://wiki.openstreetmap.org/wiki/Key:amenity', max_length=32)),
                ('image_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fvh_courier.OSMImageNote')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
