# Generated by Django 3.0.3 on 2020-02-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0012_auto_20200218_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='housenumber',
            field=models.CharField(blank=True, help_text='E.g. 3-5', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='entrance',
            name='housenumber',
            field=models.CharField(blank=True, help_text='E.g. 3-5', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='housenumber',
            field=models.CharField(blank=True, help_text='E.g. 3-5', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='housenumber',
            field=models.CharField(blank=True, help_text='E.g. 3-5', max_length=8, null=True),
        ),
    ]
