# Generated by Django 3.0.3 on 2020-02-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0013_auto_20200220_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrance',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='In meters', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='entrance',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='In meters', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='gate',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='In meters', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='gate',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='In meters', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='steps',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='In meters', max_digits=4, null=True),
        ),
    ]
