# Generated by Django 3.0.3 on 2020-03-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0015_add_sender_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrance',
            name='buzzer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrance',
            name='keycode',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrance',
            name='wheelchair',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gate',
            name='buzzer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gate',
            name='keycode',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
