# Generated by Django 3.0.4 on 2020-03-11 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fvh_courier', '0016_auto_20200309_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageNoteUpvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='fvh_courier.OSMImageNote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_note_upvotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageNoteDownvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downvotes', to='fvh_courier.OSMImageNote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_note_downvotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
