# Generated by Django 3.0.4 on 2020-03-12 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fvh_courier', '0017_imagenotedownvote_imagenoteupvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSMImageNoteComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('comment', models.TextField()),
                ('image_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='fvh_courier.OSMImageNote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_note_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
