# Generated by Django 3.0.4 on 2020-03-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0018_osmimagenotecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='osmfeature',
            name='associated_entrances',
            field=models.ManyToManyField(blank=True, related_name='associated_features', to='fvh_courier.OSMFeature'),
        ),
    ]
