# Generated by Django 3.0.4 on 2020-03-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0019_osmfeature_associated_entrances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmimagenote',
            name='osm_features',
            field=models.ManyToManyField(blank=True, related_name='image_notes', to='fvh_courier.OSMFeature'),
        ),
    ]
