# Generated by Django 3.0.4 on 2020-03-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0021_auto_20200331_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
