# Generated by Django 3.0.5 on 2020-04-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0023_auto_20200401_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='delivery_instructions',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
