# Generated by Django 3.0.5 on 2020-04-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0024_package_delivery_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
