# Generated by Django 3.0.5 on 2020-04-03 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fvh_courier', '0025_auto_20200402_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesms',
            name='message_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'courier_notification'), (1, 'reservation'), (2, 'pickup'), (3, 'delivery')]),
        ),
        migrations.CreateModel(
            name='PrimaryCourier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_primary_courier_for', to=settings.AUTH_USER_MODEL)),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='primary_courier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
