# Generated by Django 3.0.5 on 2020-04-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0026_auto_20200403_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesms',
            name='message_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'reservation'), (1, 'pickup'), (2, 'delivery'), (3, 'courier_notification')]),
        ),
        migrations.AlterField(
            model_name='packagesms',
            name='twilio_sid',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
