# Generated by Django 3.0.5 on 2020-04-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0027_auto_20200406_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='delivery_covid19',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='amenity',
            name='opening_hours_covid19',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='amenity',
            name='takeaway_covid19',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='office',
            name='opening_hours_covid19',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='shop',
            name='opening_hours_covid19',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
