# Generated by Django 3.0.5 on 2020-05-06 13:26
from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0029_auto_20200506_1325'),
    ]

    operations = [
    ]
