# Generated by Django 3.0.5 on 2020-05-07 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0030_populate_courier_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primarycourier',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='primarycourier',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='package',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='package',
            name='sender',
        ),
        migrations.AlterField(
            model_name='couriercompany',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_coordinator_for', to='fvh_courier.Courier'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='courier_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senders', to='fvh_courier.CourierCompany'),
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
        migrations.DeleteModel(
            name='PrimaryCourier',
        ),
    ]
