# Generated by Django 3.0.5 on 2020-05-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0031_auto_20200507_0751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='courier_2',
            new_name='courier',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='sender_2',
            new_name='sender',
        ),
    ]
