# Generated by Django 3.0.5 on 2020-05-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0032_auto_20200507_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='lon',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='osmimagenote',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='osmimagenote',
            name='lon',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='lon',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
    ]
