# Generated by Django 3.0.5 on 2020-05-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0033_auto_20200508_0729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
