# Generated by Django 3.0.5 on 2020-06-01 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holvi_orders', '0002_auto_20200331_1347'),
        ('fvh_courier', '0034_delete_userlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredHolviProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('holvi_shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='required_product', to='holvi_orders.HolviWebshop')),
            ],
        ),
        migrations.CreateModel(
            name='IgnoredHolviProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('holvi_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignored_products', to='holvi_orders.HolviWebshop')),
            ],
        ),
    ]
