# Generated by Django 3.0.5 on 2020-06-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0035_ignoredholviproduct_requiredholviproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesms',
            name='message_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'reservation'), (1, 'pickup'), (2, 'delivery'), (3, 'courier_notification'), (4, 'new_package')]),
        ),
    ]
