# Generated by Django 3.0.5 on 2020-06-11 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fvh_courier', '0037_infoboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='osmimagenote',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
