# Generated by Django 3.0.5 on 2020-06-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0038_osmimagenote_processed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmimagenote',
            name='lat',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='osmimagenote',
            name='lon',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
            preserve_default=False,
        ),
    ]
