# Generated by Django 3.1 on 2020-08-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0039_auto_20200626_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='housenumber',
            field=models.CharField(blank=True, help_text='E.g. 3-5', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='address',
            name='unit',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
