# Generated by Django 3.1 on 2020-08-27 10:08
import re

from django.db import migrations

street_address_regex = re.compile(
    r'^(?P<street>.+?) +(?P<housenumber>[\d\-]+( ?[a-z])?) *((?P<unit>[A-Z]{1,2})[ ,])?.*$')


def sync_street_address(self):
    if self.street_address:
        match = re.fullmatch(street_address_regex, self.street_address)
        if match and not self.street:
            self.street = match.group('street')
            self.housenumber = match.group('housenumber')
            self.unit = match.group('unit') or ''
    elif self.street and self.housenumber:
        self.street_address = f'{self.street} {self.housenumber} {self.unit or ""}'.strip()


def forwards(apps, schema_editor):
    Address = apps.get_model('fvh_courier', 'Address')
    for address in Address.objects.all():
        sync_street_address(address)
        address.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0040_auto_20200827_1217'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
