# Generated by Django 3.1 on 2020-08-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0041_sync_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='official',
            field=models.BooleanField(default=False),
        ),
    ]
