# Generated by Django 3.1 on 2020-10-19 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fvh_courier', '0045_trafficsign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmimagenotecomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_note_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
