# Generated by Django 3.1 on 2020-10-22 10:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0046_auto_20201019_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='osmimagenote',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='imagenotetag',
            name='image_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fvh_courier.osmimagenote'),
        ),
    ]
