# Generated by Django 3.1 on 2020-10-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0048_transfer_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageNoteTag',
        ),
    ]
