# Generated by Django 3.1.2 on 2020-10-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0049_delete_imagenotetag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrance',
            name='type',
            field=models.CharField(blank=True, choices=[['main', 'main'], ['secondary', 'secondary'], ['service', 'service'], ['staircase', 'staircase'], ['garage', 'garage']], max_length=32),
        ),
    ]
