# Generated by Django 3.1.4 on 2020-12-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0050_auto_20201030_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='company',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='user',
        ),
        migrations.RemoveField(
            model_name='couriercompany',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='holvipackage',
            name='package',
        ),
        migrations.DeleteModel(
            name='IgnoredHolviProduct',
        ),
        migrations.RemoveField(
            model_name='package',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='package',
            name='courier_company',
        ),
        migrations.RemoveField(
            model_name='package',
            name='deliver_to',
        ),
        migrations.RemoveField(
            model_name='package',
            name='pickup_at',
        ),
        migrations.RemoveField(
            model_name='package',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='packagesms',
            name='package',
        ),
        migrations.DeleteModel(
            name='RequiredHolviProduct',
        ),
        migrations.RemoveField(
            model_name='sender',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sender',
            name='courier_company',
        ),
        migrations.RemoveField(
            model_name='sender',
            name='user',
        ),
        migrations.DeleteModel(
            name='Courier',
        ),
        migrations.DeleteModel(
            name='CourierCompany',
        ),
        migrations.DeleteModel(
            name='HolviPackage',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='PackageSMS',
        ),
        migrations.DeleteModel(
            name='Sender',
        ),
    ]
