# Generated by Django 3.1.7 on 2021-05-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olmap', '0006_remove_unofficial_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='official',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='unit',
        ),
    ]
