# Generated by Django 3.1.7 on 2021-05-10 08:15

from django.db import migrations


def forwards(apps, schema_editor):
    Address = apps.get_model('olmap', 'Address')
    OSMFeature = apps.get_model('olmap', 'OSMFeature')

    max_address = Address.objects.order_by('-id').first()
    if not max_address:
        return
    address_features = OSMFeature.objects.filter(id__lte=max_address.id).prefetch_related('image_notes__addresses')

    for a in address_features:
        for n in a.image_notes.all():
            n.addresses.add(a.id)
    address_features.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('olmap', '0009_osmimagenote_addresses'),
    ]

    operations = [
        migrations.RunPython(forwards, lambda m, s: None)
    ]
