# Generated by Django 3.1.7 on 2021-05-12 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("olmap", "0010_link_image_note_addresses"),
    ]

    operations = [
        migrations.AddField(
            model_name="barrier",
            name="osm_feature",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="olmap.osmfeature"
            ),
        ),
        migrations.AddField(
            model_name="entrance",
            name="osm_feature",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="olmap.osmfeature"
            ),
        ),
        migrations.AddField(
            model_name="gate",
            name="osm_feature",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="olmap.osmfeature"
            ),
        ),
        migrations.AddField(
            model_name="infoboard",
            name="osm_feature",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="olmap.osmfeature"
            ),
        ),
        migrations.AddField(
            model_name="steps",
            name="osm_feature",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="olmap.osmfeature"
            ),
        ),
        migrations.AddField(
            model_name="trafficsign",
            name="osm_feature",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="olmap.osmfeature"
            ),
        ),
        migrations.AddField(
            model_name="workplace",
            name="osm_feature",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="olmap.osmfeature"
            ),
        ),
    ]
