# Generated by Django 3.1.7 on 2021-05-12 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("olmap", "0011_auto_20210512_1138"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="workplace",
            name="delivery_hours",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="workplace",
            name="delivery_instructions",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="WorkplaceEntrance",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("delivery_hours", models.CharField(blank=True, max_length=64)),
                ("delivery_instructions", models.TextField(blank=True)),
                ("delivery_types", models.ManyToManyField(blank=True, to="olmap.DeliveryType")),
                (
                    "entrance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workplace_entrances",
                        to="olmap.entrance",
                    ),
                ),
                (
                    "workplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workplace_entrances",
                        to="olmap.workplace",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UnloadingPlace",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "length",
                    models.DecimalField(blank=True, decimal_places=2, help_text="In meters", max_digits=4, null=True),
                ),
                (
                    "width",
                    models.DecimalField(blank=True, decimal_places=2, help_text="In meters", max_digits=4, null=True),
                ),
                (
                    "max_weight",
                    models.DecimalField(blank=True, decimal_places=2, help_text="In tons", max_digits=4, null=True),
                ),
                ("description", models.TextField(blank=True)),
                ("opening_hours", models.CharField(blank=True, max_length=64)),
                ("entrances", models.ManyToManyField(blank=True, related_name="unloading_places", to="olmap.Entrance")),
                ("image_note", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="olmap.osmimagenote")),
                (
                    "osm_feature",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="olmap.osmfeature"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
