# Generated by Django 3.1.7 on 2021-06-07 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olmap', '0015_unloadingplace_access_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='osmimagenote',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
