# Generated by Django 3.1.7 on 2021-10-19 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("olmap", "0017_auto_20210609_1021"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingPassage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[["footway", "footway"], ["service", "service"]],
                        default="footway",
                        max_length=32,
                    ),
                ),
                (
                    "width",
                    models.DecimalField(blank=True, decimal_places=2, help_text="In meters", max_digits=4, null=True),
                ),
                (
                    "height",
                    models.DecimalField(blank=True, decimal_places=2, help_text="In meters", max_digits=4, null=True),
                ),
                ("image_note", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="olmap.osmimagenote")),
                (
                    "osm_feature",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="olmap.osmfeature"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
