# Generated by Django 3.1.7 on 2021-10-20 09:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("olmap", "0018_buildingpassage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="osmimagenote",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), blank=True, default=list, size=None
            ),
        ),
    ]
