# Generated by Django 3.2.10 on 2021-12-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("olmap", "0022_auto_20211220_1132"),
    ]

    operations = [
        migrations.AddField(
            model_name="gate",
            name="ref",
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
