# Generated by Django 3.2.10 on 2022-02-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("olmap", "0023_gate_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="osmimagenote",
            name="layer",
            field=models.IntegerField(blank=True, help_text="Map layer, e.g. -1 if underground", null=True),
        ),
    ]
