# Generated by Django Code

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("olmap", "0026_auto_20220308_1304"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name="postal code"),
        ),
    ]
